version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: onecenter_postgres
    restart: always
    environment:
      POSTGRES_DB: OneCenter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    container_name: nginx_imagens
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/uploads
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: 2x8Ige7GhYskR0VNh2NKqrydI3X_6YbCNjfzVaEn2wUeHx14c
    command: http nginx:80
    ports:
      - "4040:4040"
