version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: onecenter_postgres
    restart: always
    environment:
      POSTGRES_DB: OneCenter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunnel
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: 2x8Ige7GhYskR0VNh2NKqrydI3X_6YbCNjfzVaEn2wUeHx14c
    command: http host.docker.internal:8080
    ports:
      - "4040:4040" # acesso ao dashboard do ngrok
